---
title: "new project"
output: html_document
date: "2025-10-22"
---

## Step 1 = Data cleaning and preparation

### 1
```{r}

library(dplyr)
library(readr)

data = read_csv("adult.csv", na = "?")

data

colSums(is.na(data))

```





```{r}
colSums(is.na(data))
# see how many "NA value" is in the data frame
```


```{r}
# Handle the missing values using the most frequent value of each column

table(data$workclass)

data$workclass[is.na(data$workclass)] = "Private"


```

```{r}
# Handle the missing values using the most frequent value of each column

categories <- na.omit(unique(data$occupation))
 
idx_na <- which(is.na(data$occupation))
 
n_na <- length(idx_na)
 
replacement <- rep(categories, length.out = n_na)
 
set.seed(42)
replacement <- sample(replacement)
 
data$occupation[idx_na] <- replacement
 
head(data)



```

```{r}
table(data$education, data$education.num)
#check if is there any differnt match in edu and edu.num group
inconsistent_rows <- data %>%
  group_by(education, education.num) %>%
  summarise(count = n()) %>%
  filter(n() > 1)

print(inconsistent_rows)

#choose to use the number
data <- data %>% select(-education)

```
```{r}
unique(data$workclass)
```


#Categorical variables
```{r}

data <- data %>%
  mutate_if(is.character, trimws)

unique(data$occupation)
```

#Step 2



























